### ISSUE TITLE
Socket reuse flag not working?

### ISSUE THREAD

**Issue by redterror** [stripe/einhorn#45]
Hi - I'm running einhorn via upstart and I'm seeing the following exception if there is a stop/start sequence in rapid succeession:

```
Mar 12 19:13:13 doughnut goliath-channel_api: [MASTER 29092] INFO: Writing PID to /srv/www/channel_api/shared/pids/einhorn.pid
Mar 12 19:13:13 doughnut goliath-channel_api: [MASTER 29092] INFO: Binding to 0.0.0.0:8080 with flags ["rn"]
Mar 12 19:13:13 doughnut goliath-channel_api: [MASTER 29092] INFO: Sending USR2 to []
Mar 12 19:13:13 doughnut goliath-channel_api: /home/deploy/.bundler/channel_api/ruby/2.1.0/gems/einhorn-0.6.3/lib/einhorn.rb:205:in `bind': Address already in use - bind(2) for 0.0.0.0:8080 (Errno::EADDRINUSE)
Mar 12 19:13:13 doughnut goliath-channel_api: #011from /home/deploy/.bundler/channel_api/ruby/2.1.0/gems/einhorn-0.6.3/lib/einhorn.rb:205:in `bind'
Mar 12 19:13:13 doughnut goliath-channel_api: #011from /home/deploy/.bundler/channel_api/ruby/2.1.0/gems/einhorn-0.6.3/lib/einhorn.rb:356:in `block in socketify_env!'
Mar 12 19:13:13 doughnut goliath-channel_api: #011from /home/deploy/.bundler/channel_api/ruby/2.1.0/gems/einhorn-0.6.3/lib/einhorn.rb:355:in `each'
Mar 12 19:13:13 doughnut goliath-channel_api: #011from /home/deploy/.bundler/channel_api/ruby/2.1.0/gems/einhorn-0.6.3/lib/einhorn.rb:355:in `socketify_env!'
Mar 12 19:13:13 doughnut goliath-channel_api: #011from /home/deploy/.bundler/channel_api/ruby/2.1.0/gems/einhorn-0.6.3/lib/einhorn.rb:449:in `run'
Mar 12 19:13:13 doughnut goliath-channel_api: #011from /home/deploy/.bundler/channel_api/ruby/2.1.0/gems/einhorn-0.6.3/bin/einhorn:327:in `<top (required)>'
Mar 12 19:13:13 doughnut goliath-channel_api: #011from /home/deploy/.bundler/channel_api/ruby/2.1.0/bin/einhorn:23:in `load'
Mar 12 19:13:13 doughnut goliath-channel_api: #011from /home/deploy/.bundler/channel_api/ruby/2.1.0/bin/einhorn:23:in `<main>'
```

When the error is reported, there are no running einhorn processes but `netstat -na | grep 8080` reports a few sockets in TIME_WAIT.  I thought the `r` flag should let einhorn bind despite that?

**Comment by ebroder** [comment]
I think individual flags have to be comma-separated - does it work if you pass `-b 0.0.0.0:8080,r,n` instead of `,rn`?

**Comment by redterror** [comment]
It does!  I tried it with just `r` previously, but, whatever, works.  Thanks!
