### ISSUE TITLE
Einhorn with Goliath

### ISSUE THREAD

**Issue by tumayun** [stripe/einhorn#56]
Hello

I do not know how to achieve a seamless restart Goliath.
Please give me some advice, thank you!

```
einhorn -n 2 -b 127.0.0.1:3000 ruby app.rb --einhorn
[MASTER 16379] INFO: Writing PID to /var/folders/nc/2jhfmrs55fz7qkqddw5cvtkw0000gn/T/einhorn.pid
[MASTER 16379] INFO: Binding to 127.0.0.1:3000 with flags []
[MASTER 16379] INFO: Launching 1 new workers
[MASTER 16379] INFO: ===> Launched 16380 (index: 0)
[WORKER 16380] INFO: About to exec ["/Users/tumayun/.rvm/rubies/ruby-2.2.3/bin/ruby", "app.rb", "--einhorn"]
[MASTER 16379] INFO: Worker 16380 has been up for 1s, so we are considering it alive.
[MASTER 16379] INFO: Up to 1 / 1 timer ACKs
/Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/runner.rb:107:in `initialize': invalid option: --einhorn (OptionParser::InvalidOption)
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/application.rb:107:in `new'
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/application.rb:107:in `run!'
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/application.rb:133:in `block in <module:Goliath>'
[MASTER 16379] INFO: ===> Exited worker 16380
[MASTER 16379] INFO: ===> Launched 16382 (index: 0)
[WORKER 16382] INFO: About to exec ["/Users/tumayun/.rvm/rubies/ruby-2.2.3/bin/ruby", "app.rb", "--einhorn"]
/Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/runner.rb:107:in `initialize': invalid option: --einhorn (OptionParser::InvalidOption)
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/application.rb:107:in `new'
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/application.rb:107:in `run!'
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/application.rb:133:in `block in <module:Goliath>'
[MASTER 16379] INFO: ===> Exited worker 16382 before it was ACKed
```

And

```
einhorn -n 2 -b 127.0.0.1:3000 ruby app.rb -sv
[MASTER 16434] INFO: Writing PID to /var/folders/nc/2jhfmrs55fz7qkqddw5cvtkw0000gn/T/einhorn.pid
[MASTER 16434] INFO: Binding to 127.0.0.1:3000 with flags []
[MASTER 16434] INFO: Launching 2 new workers
[MASTER 16434] INFO: ===> Launched 16435 (index: 0)
[WORKER 16435] INFO: About to exec ["/Users/tumayun/.rvm/rubies/ruby-2.2.3/bin/ruby", "app.rb", "-sv"]
[MASTER 16434] INFO: ===> Launched 16436 (index: 1)
[WORKER 16436] INFO: About to exec ["/Users/tumayun/.rvm/rubies/ruby-2.2.3/bin/ruby", "app.rb", "-sv"]
[16435:INFO] 2015-11-30 23:27:34 :: Starting server on 0.0.0.0:9000 in development mode. Watch out for stones.
[16436:INFO] 2015-11-30 23:27:34 :: Starting server on 0.0.0.0:9000 in development mode. Watch out for stones.
/Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/eventmachine-4de7d0e00fe8/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/eventmachine-4de7d0e00fe8/lib/eventmachine.rb:526:in `start_server'
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/bundler/gems/goliath-5d0b54543705/lib/goliath/server.rb:86:in `block in start'
    from /Users/tumayun/.rvm/gems/ruby-2.2.3/gems/em-synchrony-1.0.4/lib/em-synchrony.rb:38:in `block (2 levels) in synchrony'
[MASTER 16434] INFO: ===> Exited worker 16436 before it was ACKed
[MASTER 16434] INFO: Worker 16435 has been up for 1s, so we are considering it alive.
[MASTER 16434] INFO: Up to 1 / 2 timer ACKs, breaking the streak of 1 consecutive unacked workers dying
^C[MASTER 16434] INFO: ===> Exited worker 16435
```

**Comment by ACirnici** [comment]
Hey, got the same problem. Did you manage to resolve it?
